### ISSUE TITLE
Error in script

### ISSUE THREAD

**Issue by sanswitcher** [erikw/ewxb_gcc_cross-compiler_builder#4]
I've found a small error in the ewxb-script:

line 217:
$sysroot
ist wrong and empty.
Replace it with
$SYSROOT (capital letters).

**Comment by erikw** [comment]
Thanks!

**Comment by sanswitcher** [comment]
Hi,

It's really a nice script!

I'm using it to understand the several steps to get a working cross 
compiler.

At the the moment I have added fortran+openmp (that's what I'm 
interested in mainly),
but the start of the binary fails because of a wrong libc.so version.

regards
Eberhard

-- 
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by erikw** [comment]
I hope this script can give some pointers on the general steps needed. There are however many details that will probably differ for you :)
